apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  annotations:
    kubernetes.io/change-cause: 'Version 1.13'
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.15
          name: nginx-server
          ports:
            - containerPort: 80
